/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_nativeegl_MyRenderer */
#include <string.h>

#define __cplusplus

#ifndef _Included_com_example_nativeegl_MyRenderer
#define _Included_com_example_nativeegl_MyRenderer

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_nativeegl_MyRenderer
 * Method:    nativeGetHelloString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_nativeegl_MyRenderer_nativeGetHelloString
  (JNIEnv *, jobject);

/*
 * Class:     com_example_nativeegl_MyRenderer
 * Method:    nativeDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_nativeegl_MyRenderer_nativeDrawFrame
  (JNIEnv *, jobject);

/*
 * Class:     com_example_nativeegl_MyRenderer
 * Method:    nativeSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_nativeegl_MyRenderer_nativeSurfaceChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_nativeegl_MyRenderer
 * Method:    nativeSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_nativeegl_MyRenderer_nativeSurfaceCreated
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
